export { BaseProfile, defineProfile, parseRawBytes } from './base';
export { deriveOptionalServices } from './services';
export type { OptionalServicesSource, ProfileWithServices } from './services';
export { HeartRateProfile, parseHeartRate, HEART_RATE_SERVICES } from './heart-rate';
export type { HeartRateData } from './heart-rate';
export { BatteryProfile } from './battery';
export { DeviceInfoProfile } from './device-info';
export type { DeviceInfo } from './device-info';
export { NordicUARTProfile, NUS_SERVICES } from './nordic-uart';
export { HM10SerialProfile } from './serial-ffe0';
